version: '1.0'
name: pipeline-20220820
displayName: pipeline-20220820
triggers:
  trigger: auto
  push:
    branches:
      include:
        - '**/*src/**/*.java'
stages:
  - name: stage-05a07953
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@maven
        name: build_maven
        displayName: Maven 构建
        jdkVersion: '8'
        mavenVersion: 3.3.9
        commands:
          - mvn -B package --file pom.xml
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./target
        settings: []
        caches:
          - ~/.m2
        notify: []
        strategy:
          retry: '0'
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        dependArtifact: BUILD_ARTIFACT
        artifactName: ZeroKingBot
        notify: []
        strategy:
          retry: '0'
  - name: stage-e84a7545
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: publish@release_artifacts
        name: publish_release_artifacts
        displayName: 发布
        dependArtifact: ZeroKingBot
        version: 4.1.7.3
        autoIncrement: true
        notify: []
        strategy:
          retry: '0'
