name: Publish package to GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Maven Release and Publish
        # You may pin to the exact commit or the version.
        # uses: mg-smartrent/github-actions-maven-release@5f387c0d77b22da293e9812d43ab90cdc49f475a
        uses: mg-smartrent/github-actions-maven-release@v1.5
        with:
          # Filter the branch to execute the release on
          release-branch-name: main # optional
          # The git user name for commiting the release
          git-release-bot-name: KingPrimes
          # The git user email for commiting the release
          git-release-bot-email: Sakitama_q@163.com
          # Github access token. https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line
          access-token: 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
